#!/usr/bin/env bash
# shellcheck disable=SC2016
# configures ubuntu server with custom header

sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart
