#!/usr/bin/env bash
# a bash script that installs nginx webserver
sudo apt-get -y update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y install haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

{
echo -e "\
frontend web_frontend
\tbind *:80
\tmode http
\tdefault_backend web_backend
backend web_backend
\tbalance roundrobin
\tserver 61817-web-01 54.237.44.150:80 check
\tserver 61817-web-02 100.25.0.186:80 check"
} | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
