#!/usr/bin/env bash
# shellcheck disable=SC2016
# installing and config load balancer
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7
sudo apt-get -y update
sudo apt-get -y install haproxy=2.7.\*

echo "ENABLED=1" >> /etc/default/haproxy

echo "
frontend load_balancer
    bind *:80
    mode http
    default_backend webserver
backend webserver
    balance roundrobin
    server 64396-web-01 34.201.165.150:80 check
    server 64396-web-02 100.26.121.251:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
