#!/usr/bin/env bash
# Installs  sql after getting key from https://dev.mysql.com/doc/refman/5.7/en/checking-gpg-signature.html
sudo apt-key add mysql_pubkey.asc
sudo sh -c 'echo "deb http://repo.mysql.com/apt/ubuntu bionic mysql-5.7" >> /etc/apt/sources.list.d/mysql.list'
sudo apt-get update
sudo apt install -f mysql-client=5.7* mysql-community-server=5.7* mysql-server=5.7*


