#!/bin/bash
vi 0-current_working_directory  
vi 14-copy_html     
vi 5-listfilesdigitonly  
vi 10-back                      
vi 1-listit         
vi 6-firstdirectory
vi 11-lists                     
vi 2-bring_me_home  
vi 7-movethatfile
vi 12-file_type                 
vi 3-listfiles      
vi 8-firstdelete
vi 13-symbolic_link             
vi 4-listmorefiles  
vi 9-firstdirdeletion
