#!/usr/bin/env bash
# creates a file /var/run/myscript.pid stores file pid traps signals
# SIGTERM SIGINT AND SIGQUIT removing the file on SIGTERM AND SIGQUIT

touch /var/run/myscript.pid
echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid; exit' SIGQUIT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
