#!/usr/bin/env bash
#fizzbuzz in bash
for (( i=1; i<=100; i++))
do
    div3=$((i % 3 == 0))
    div5=$((i % 5 == 0))
    if ((i % 15 == 0))
    then
        echo "FizzBuzz"
    elif ((div3))
    then
        echo "Fizz"
    elif ((div5))
    then
        echo "Buzz"
    else
        echo "$i"
    fi
done
