#!/usr/bin/env bash
#fizzbuzz in bash
for (( i=1; i<=100; i++))
do
	div3=$((i % 3))
	div5=$((i % 5))
	if ((i % 15 == 0))
	then
		echo "FizzBuzz"
	elif ((div3 == 0))
	then
		echo "Fizz"
	elif ((div5 == 0))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
