#!/usr/bin/env bash
#read from file and printout something
while IFS=: read -r -a content
do
    echo "The user ${content[0]} is part of the ${content[3]} gang, lives in ${content[5]} and rides ${content[6]}. ${content[2]}'s place is protected by the passcode ${content[1]}, more info about the user here: ${content[4]}"
done < "/etc/passwd"
