#!/usr/bin/env bash
#displays time from 0 to 12 59 hours minutes
i=1
while ((i <= 20))
do
	case $i in
		4)
			echo "bad luck from China"
		;;
		9)
			echo "bad luck from Japan"
		;;
		17)
			echo "bad luck from Italy"
		;;
		*)
			echo "$i"
		;;
	esac
	((i++))
done
