#!/usr/bin/env bash
#displays time from 0 to 12 59 hours minutes
hour=0
while ((hour <= 12))
do
	minute=1
	echo "Hour: $hour"
	while ((minute <= 59))
	do
		echo "$minute"
		((minute++))
	done
	((hour++))
done
